

version: '3.8'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      - DB_USER=task_user
      - DB_PASS=password
      - DB_HOST=postgres
      - DB_NAME=task_tracker
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
